#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
su -s /bin/bash -c "/usr/sbin/nginx" nginx
