#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
useradd --no-create-home --shell /bin/false nginx
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
nginx -s stop
nginx
