#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
pkill -f nginx
sleep 1
sudo -u nginx nginx
