#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i 's|server_name _;|server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|' /etc/nginx/sites-enabled/default

service nginx restart
